api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    resource_class_directories:
        - '%kernel.project_dir%/src/Domain/Entity'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
